### ISSUE TITLE
Using tRemedy

### ISSUE THREAD

**Issue by csgonzaga** [johanwasserman/tRemedy#2]
Helo, 

Do you have same tutorial about how to use tRemedy.
I don´t know nothing about programmers and I am beginner in Talend.
I get the error below:

Exception in component tRemedyIn_1
java.lang.NullPointerException
    at local_project.remedy_0_1.Remedy.tSetGlobalVar_1Process(Remedy.java:887)
    at local_project.remedy_0_1.Remedy.runJobInTOS(Remedy.java:1608)
    at local_project.remedy_0_1.Remedy.main(Remedy.java:1465)

Thanks for now!
Carlos

**Comment by johanwasserman** [comment]
Carlos, I'm working on a tutorial.

I will need t some context to understand why you get the error, can you
send me your job or some screenshots of it?
